# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-debug:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone xpinstaller
      run: cd .. && sudo rm -rf buildxposedinstallerinaction && git clone https://github.com/rovo89/XposedInstaller.git buildxposedinstallerinaction
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: mkdir
      run: mkdir out
    - name: set up JDK 9
      run: sudo apt install openjdk-9-jdk
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk out/app-debug.apk
    - name: Upload APK(debug)
      uses: actions/upload-artifact@v3
      with:
          name: app
          path: out/app-debug.*
